default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: academyquest_dev

test:
  <<: *default
  database: academyquest_test

production:
  primary:
    <<: *default
    database: academyquest_prod
    host: 10.11.0.202
  cache:
    <<: *default
    database: academydb_prod_cache
    host: 10.11.0.202
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: academydb_prod_queue
    host: 10.11.0.202
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: academydb_prod_cable
    host: 10.11.0.202
    migrations_paths: db/cable_migrate
